### ISSUE TITLE
2016-03-21 : WordPress meetup Antwerpen

### ISSUE THREAD

**Issue by TSchuermans** [nucleus-be/office-meetups#1]
**Contact** : Dave Loodts (@daveloodts), Veerle Verbert
**Talk 1** : Tom Hermans (@tomhermans) - De WordPress REST API
**Talk 2** : Mattias Geniar (@mattiasgeniar) - HTTP/2 for WordPress developers
**Meetup page** : http://www.meetup.com/Antwerp-WordPress-Meetup/events/229418947/
**Tweet** : https://twitter.com/wpantwerp/status/709413847191437313
**RSVP rate** : 23/50 (expected: 33, rate: +- 70%)
**Parking space** :
![Parking space](https://raw.githubusercontent.com/nucleus-be/office-meetups/master/parking_space.png)

**Todo** :
- [x] share on social media
- [x] notify concierge
- [x] order food / drinks
- [x] share parking space image on social media
- [x] ug flyers with directions
- [x] ...
- [x] profit!

**Comment by mattiasgeniar** [comment]
Meetup link : http://www.meetup.com/Antwerp-WordPress-Meetup/events/229418947/

**Comment by daveloodts** [comment]
Dag Tom,

Ik ga deze woensdag nog een tweede call uitsturen voor RSVP.
Dan kunnen we op vrijdag zien hoeveel personen er zullen komen; ook betreft
de catering.
Weet wel; dat we meestal zo'n 10% no shows hebben.

Sinds vorige week is ook de website van WordCamp Antwerp live gegaan.
Indien jullie interesse hebben in sponsoren of een talk; geef gerust een
seintje.
Of we bespreken dit volgende week maandag.

https://2016.antwerp.wordcamp.org/

Nogmaals dank voor jullie support.

Met vriendelijke groeten,
Dave Loodts
www.davel.be

2016-03-09 9:54 GMT+01:00 Mattias Geniar notifications@github.com:
