### ISSUE TITLE
2016-10-26 : PHP Antwerp meetup

### ISSUE THREAD

**Issue by TSchuermans** [nucleus-be/office-meetups#12]
**Contact** : Dries Vints (@driesvints)
**Talk 1** : Mattias Geniar - Varnish for PHP Developers
**Talk 2** : Mattias Geniar - Live coding session?
**Meetup page** : http://www.meetup.com/phpantwerp/events/233732065/
**Tweet** : https://twitter.com/phpantwerp/status/786575575112617984
**Joind.in page** : https://joind.in/event/php-antwerp---october-meetup
**RSVP rate** : ?/20
**Parking space** :
![Parking space](https://raw.githubusercontent.com/nucleus-be/office-meetups/master/parking_space.png)

**Todo** :
- [x] share on social media
- [x] notify concierge
- [x] order food / drinks
- [x] share parking space image on social media
- [x] ug flyers with directions
- [x] ...
- [x] profit!

**Comment by driesvints** [comment]
@TSchuermans first talk added: http://www.meetup.com/phpantwerp/events/233732065/
