### ISSUE TITLE
2016-06-29 : PHP Antwerp meetup

### ISSUE THREAD

**Issue by TSchuermans** [nucleus-be/office-meetups#3]
**Contact** : Dries Vints (@driesvints)
**Talk 1** : Freek Van der Herten - Taking care of backups with Laravel
**Talk 2** : Gabriel Somoza - First Steps with Event Sourcing
**Meetup page** : http://www.meetup.com/phpantwerp/events/229943095/
**Tweet** : https://twitter.com/nucleus_hosting/status/744827363435941888
**Joind.in page** : https://joind.in/event/php-antwerp---june-meetup
**RSVP rate** : ?/50
**Parking space** :
![Parking space](https://raw.githubusercontent.com/nucleus-be/office-meetups/master/parking_space.png)

**Todo** :
- [x] share on social media
- [x] notify concierge
- [x] order food / drinks
- [x] share parking space image on social media
- [x] ug flyers with directions
- [x] ...
- [x] profit!

**Comment by driesvints** [comment]
If possible, we can do this the end of may? On the 24th (a Tuesday).

**Comment by TSchuermans** [comment]
Slot is still open, so fine by me.

**Comment by driesvints** [comment]
Heya, is it possible to postpone this by one month so it's on the 29th of june? Problem is that I forgot we already scheduled a meetup at MCS. So sorry about this! Let me know if this is ok with you so we can start arranging speakers :smile:

**Comment by mattiasgeniar** [comment]
No problem, 29th of June is still open.

**Comment by driesvints** [comment]
Ok great! I've made the meetup page. I'll start looking for speakers. I think Michelangelo wanted to speak so I'll contact him. @TSchuermans @mattiasgeniar you guys also want to deliver a talk? :smile:  You're always free to do a short one as well (15-30 minutes?).

**Comment by driesvints** [comment]
http://www.meetup.com/phpantwerp/events/229943095/

**Comment by mattiasgeniar** [comment]
Ping me again a month in advance, I'll see if I have time/"goesting" to do to a talk then :)
This is foo far in advance to know for sure :P

**Comment by driesvints** [comment]
@mattiasgeniar ok, will do!

**Comment by driesvints** [comment]
We have a first talk! http://www.meetup.com/phpantwerp/events/229943095/

@mattiasgeniar if it's ok with you I'm going to contact Michelangelo for the second talk. We'll work something out for a future meetup so you can talk again! :)

**Comment by driesvints** [comment]
Btw, this repo gave me the great idea to start a similar one for PHP Antwerp: https://github.com/phpantwerp/meetups

Thanks for the inspiration! :smile:

**Comment by driesvints** [comment]
Second speaker announced: Gabriel Somoza will be talking about Event Sourcing. We'll probably also try to live stream the talks if that's ok with you?

http://www.meetup.com/phpantwerp/events/229943095/

Let me know if there's anything more you need.

Looking forward to next week! 😄

**Comment by driesvints** [comment]
I've also requested the Joind.in page so should be ready soon.

**Comment by TSchuermans** [comment]
@driesvints Nice!
Live streaming should be no problem at all.
We'll order sandwiches and drinks on monday when we have a clear RSVP count.

**Comment by driesvints** [comment]
Joind.in page: https://joind.in/event/php-antwerp---june-meetup
