### ISSUE TITLE
2016-05-25 : Drupal User Group Belgium meetup

### ISSUE THREAD

**Issue by TSchuermans** [nucleus-be/office-meetups#8]
**Contact** : Sven Decabooter (@svendecabooter)
**Talk** : Joris Vercammen - Search API eco system in Drupal 8 
**Meetup page** : http://www.meetup.com/DUG-BE/events/230291730/
**Tweet** : https://twitter.com/sdecabooter/status/733203957607239680
**RSVP rate** : 16/50
**Parking space** :
![Parking space](https://raw.githubusercontent.com/nucleus-be/office-meetups/master/parking_space.png)

**Todo** :
- [x] share on social media
- [x] notify concierge
- [x] order food / drinks
- [x] share parking space image on social media
- [x] ug flyers with directions
- [x] ...
- [x] profit!

**Comment by svendecabooter** [comment]
Hi Tom,

Zou do 21 april een optie zijn? Ik heb een mogelijke spreker voor een DUG in Antwerpen.
Edit: datum past niet voor spreker... ik doe ander voorstel. 

Sven

**Comment by TSchuermans** [comment]
Aight @svendecabooter, keep me posted :+1:

**Comment by svendecabooter** [comment]
@TSchuermans: is woensdag 25 mei haalbaar?

**Comment by TSchuermans** [comment]
@svendecabooter Slot is still open, so fine by me

**Comment by svendecabooter** [comment]
Meetup event is alvast aangemaakt: http://www.meetup.com/DUG-BE/events/230291730/

**Comment by svendecabooter** [comment]
@TSchuermans ik ben de komende 2 weken op reis - moet voor deze DUG nog iets praktisch geregeld worden?

**Comment by TSchuermans** [comment]
@svendecabooter Nope, we'll take care of the rest, enjoy your vacation.
